# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !

. /etc/profile

umask 077

export GTK_IM_MODULE=xim # force gtk to use the standard compose sequences
export ECHANGELOG_USER="Daniel Scharrer <daniel@constexpr.org>"

export PATH="$HOME/.void/bin:$HOME/Games/bin:$PATH"

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# Put your fun stuff here.

alias ☭='echo "Hello there, comrade!"'
alias ?='grep -P'
alias ??='grep -rP'
alias ???='grep -rPzo'
alias p='aoss postal2awp'
alias mplayer2='mplayer2 -msgcolor'
alias nokeygrab=~/.void/x11/nokeygrab.c
enter() { mkdir -p "$1" && cd "$1"; }
alias cdg='cd "$(git rev-parse --show-toplevel)"'

HISTSIZE=100000
bind '"\e[A"':history-search-backward
bind '"\e[B"':history-search-forward

PS1="\[\033[01;32m\]\u@\h\[\033[01;34m\] \W \$\[\033[00m\] "

if [ $TERM = "xterm" ] ; then
    export TERM=xterm-256color
fi
