#!/bin/sh

# Prevents commit if there untracked files that are not in .gitignore
# To use this, copy to .git/hooks/pre-commit

red='' ; white='' ; reset=''
if [ -t 1 ] && [ `tput colors` != -1 ] ; then
	red=`printf '\033[1;31m'`
	white=`printf '\033[1;37m'`
	reset=`printf '\033[0m'`
fi

untracked=`git status -u | grep '^# Untracked files:$'`
if [ "$untracked" != "" ] ; then
	git status ; echo "${red}Add untracked files first!${reset}"
	echo "Use the ${white}--no-verify${reset} option to commit anyway."
	exit 1
fi

# curse you, KDevelop
if [ -d src ] ; then
	if [ -d tools ]
		then set -- src tools
		else set -- src
	fi
	check="$(grep -rP --color 'boost\/concept_check\.hpp' "$@")"
	if [ "$check" != '' ] ; then
		echo "$red$check$reset"
		exit 1
	fi
fi
