#!/bin/sh

has() {
	which "$1" &> /dev/null
}

step() {
	echo -e "\033[1;34m=====> \033[1;32m$1\033[0m"
}

step 'Syncing Portage Tree'
emerge --sync --quiet

if has layman ; then
	step 'Syncing Overlays'
	layman --sync-all --quiet
fi

if has eix-update || has q ; then
	step 'Updating Cache'
	has eix-update && eix-update --quiet
	has q && q --reinitialize --metacache
fi

step 'Updating Portage'
emerge --update --quiet-build sys-apps/portage

step 'Updating Config Files'
dispatch-conf

step 'Updating Packages'
emerge -avDNu --quiet-build --keep-going @world || exit

step 'Updating Preserved Packages'
emerge -av --quiet-build --keep-going @preserved-rebuild

step 'Updating Config Files'
dispatch-conf

step 'Cleaning Unused Dependencies'
emerge --ask --depclean

if has lafilefixer ; then
	step 'Fixing .la Files'
	lafilefixer --justfixit > /dev/null
fi

step 'Checking Linking Consistency'
revdep-rebuild -- --ask --verbose --quiet-build --keep-going

if has prelink ; then
	step 'Pre-Linking'
	prelink -amR > /dev/null
fi

step 'Mooing'
emerge --moo
